const commentConstants = {
  CREATE_COMMENT: "CREATE_COMMENT",
  CREATE_COMMENT_LOADING: "CREATE_COMMENT_LOADING",

  RESET_COMMENTS: "RESET_COMMENTS",

  COMMENTS_ARE_LOADING: "COMMENTS_ARE_LOADING",
  COMMENTS_LOADED: "COMMENT_LOADED",
};

export default commentConstants;
