export const userConstants = {
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGIN_LOGOUT: "LOGIN_LOGOUT",
  LOGIN_FAILURE: "LOGIN_FAILURE",

  FETCH_USER_VOTES_SUCCESS:'FETCH_USER_VOTES_SUCCESS',

  REGISTER_REQUEST: "REGISTER_REQUEST",
  REGISTER_SUCCESS: "REGISTER_SUCCESS",
  REGISTER_FAILURE: "REGISTER_FAILURE",
};
