const userConstants = {
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGIN_LOGOUT: "LOGIN_LOGOUT",
  LOGIN_FAILURE: "LOGIN_FAILURE",

  FETCH_USER_VOTES: "FETCH_USER_VOTES",

  UPDATE_USER_AVATAR: "UPDATE_USER_AVATAR",

  REGISTER_REQUEST: "REGISTER_REQUEST",
  REGISTER_SUCCESS: "REGISTER_SUCCESS",
  REGISTER_FAILURE: "REGISTER_FAILURE",
};

export default userConstants;
